
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
family = "MesloLGSDZ Nerd Font Mono"

[font.offset]
x = 0
y = -1

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window.padding]
x = 0
y = 1

[general]
import = ["/home/david/.config/alacritty/solarized_dark.toml"]
